name: Weekly Strava Data Update

on:
  schedule:
    # Run at midnight PST on Friday (8 AM UTC Friday)
    - cron: '0 8 * * 5'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-strava-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}" > .env
          echo "STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}" >> .env
          echo "STRAVA_REFRESH_TOKEN=${{ secrets.STRAVA_REFRESH_TOKEN }}" >> .env

      - name: Run data collection script
        run: python src/data_collection.py

      - name: Run commute analyzer
        run: python src/commute_analyzer.py

      - name: Run visualization scripts
        run: |
          python src/visualization.py
          python src/plotly_visualizations.py
          python src/wrapped_summary.py

      - name: Remove .env file
        run: rm -f .env

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push if changed
        run: |
          git add data/activities.json output/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Strava data and visualizations [skip ci]" && git push) 